nome = input("Digite seu nome: ")
altura = float(input("Digite sua altura: "))
peso = float(input("Digite seu peso "))
imc = peso / (altura * altura)
print(nome, "tem",altura, "de altura," )
print("pesa ",peso, "quilos e seu imc é")
print(imc)
